### ISSUE TITLE
添加网站的方向讨论~

### ISSUE THREAD

**Issue by Xuanwo** [Xuanwo/WebsitesForStudents#13]
我们不可能做成一个网址大全，得有针对性，正如这个库的名字所说，我们得突出大学生这个重点
_大学生泛指一切高中阶段往后的教育阶段，包括本科，研究生，博士等等_

我觉得添加的网站大概是两个方向吧，一个是能**提供知识**，一个是指导如何**利用知识**

你们的意向如何？

**Comment by vander1997** [comment]
cool！
