### ISSUE TITLE
第四波

### ISSUE THREAD

**Issue by alex741144175** [Xuanwo/WebsitesForStudents#18]
这次的在我个人分类里都是博客
*未检查重复

-----------------------------------------------
- [ ] http://tvfantasy.net/ 这个不知道算不算，但是我觉得还是比较严谨的娱乐内容/天涯小筑
- [ ] http://blog.sciencenet.cn/blog.php 科学网 里面有很多好博客 可以自己找感兴趣的
- [ ] http://blog.sina.com.cn/u/1180557177 人类学相关
- [ ] http://blog.sina.com.cn/u/2377522840 台大历史系吕世浩教授
- [ ] http://evilsay.cc/ 安全圈的大牛
- [ ] https://glyph.twistedmatrix.com/ 好像是编程相关？
- [ ] http://datagenetics.com/blog.html datagenetics 数据类？
- [ ] http://www.gatesnotes.com/ 盖茨的
- [ ] http://www.leica.org.cn/ leica中文摄影杂志
- [ ] http://blog.sina.com.cn/benzoumeiguo 美国相关(留学)
- [ ] http://www.zerohedge.com/ 新闻博客 偏财经
- [ ] http://io9.com/ 科幻博客
- [ ] http://grammarist.com/ 语法博客
- [ ] http://www.dictionaryofobscuresorrows.com/ 一个发生僻词的tumblr
- [ ] http://www.fantxi.com/blog/ 专注于web前端开发的博客
- [ ] http://www.valleytalk.org/ 弯曲评论
- [ ] http://www.shuax.com/ “专注小巧免费实用软件”的博客
- [ ] http://www.cnblogs.com/index-html 关于编程的博客
- [ ] http://jixun.org/ 技术类博客 小技巧小工具
- [ ] https://xiaolan.me/ 技术类 但是反共
- [ ] http://blog.codinghorror.com/ 编程类
- [ ] http://smilejay.com/ 编程类
- [ ] http://www.datapointed.net/ 数据类？主要是结果展示 教程内容不多
- [ ] http://www.ruanyifeng.com/blog/ 编程
- [ ] http://www.williamlong.info/ 技术类
- [ ] http://www.joelonsoftware.com/ 编程
- [ ] http://codeblog.jonskeet.uk/ 编程
- [ ] http://worm.cc/ 安全界大牛
- [ ] http://www.hackersoul.com/ 安全类
- [ ] http://www.boydwang.com/ 技术类
- [ ] http://terrytao.wordpress.com/ 陶哲轩的博客 此人智商第二？
- [ ] http://tylervigen.com/ 有趣的统计学图
- [ ] http://blog.harwardcommunications.com/ 语法
- [ ] http://www.ha97.com/ 运维
- [ ] http://program-think.blogspot.com/ 啥都有 质量高 反共
- [ ] http://bytesizebio.net/ 生物学
- [ ] http://www.genekeyes.com/ 有世界语内容

**Comment by Xuanwo** [comment]
Down
