### ISSUE TITLE
不合格网站反馈

### ISSUE THREAD

**Issue by Xuanwo** [Xuanwo/WebsitesForStudents#24]
给大家拜一个早年啊，哈哈，祝大家来年身体健康，过年怒抢千万红包。
因为面临期末考试淫威，好久都没有来看这个库了，star的人已经达到了74个，真的是非常开心，感谢大家的支持和帮助。

下一步的目标主要有二：
- **清除不合格的网站**
- **完善各个学科的内容**

**不合格网站定义**
- 有版权问题或提供带有版权问题资源下载的
- 带有不健康信息的
- 非原创或以转载为主的
- 页面失效

**完善学科内容**
由于github本身就是一个程序员聚集的地方，所以我们不意外的发现，列表里面大多都是程序员经常去的网站。这并不坏，但是与我们这个库的主题有些偏差。我们致力于为大学生们提供一个有用的可靠的网址库，尽可能覆盖大部分专业的需求。

**Comment by lushl9301** [comment]
:+1:

**Comment by haoyuchen1992** [comment]
MoviePanda 在线电影观看  -- 这个页面失效了

**Comment by Xuanwo** [comment]
@haoyuchen1992 抱歉没注意到你的反馈，已经fix了

**Comment by Xuanwo** [comment]
Done with https://github.com/Xuanwo/WebsitesForStudents/issues/46
