### ISSUE TITLE
sb

### ISSUE THREAD

**Issue by liqile** [Xuanwo/WebsitesForStudents#26]

**Comment by lushl9301** [comment]
leave your question please, instead of your name :smile:

**Comment by Xuanwo** [comment]
什么玩意儿- -

**Comment by lushl9301** [comment]
bu yao li ta... ta yi wei zhe ge shi wo de repo....
wo peng you

**Comment by zhaochunqi** [comment]
好无语啊，我一直watch这个repo，结果你的朋友上来就这样。好影响心情。

**Comment by lushl9301** [comment]
close le bu jiu hao le... ta gen wo kai wan xiao ne....sorry about that

**Comment by liqile** [comment]
@lushl9301 sb

**Comment by liqile** [comment]
@lushl9301 我还以为是你的repo

**Comment by lushl9301** [comment]
Just close it... some mistake. That's it.
Let's keep moving~

**Comment by zhaoweiwang** [comment]
这么叼...
