### ISSUE TITLE
关于开启一个程序员专栏的讨论

### ISSUE THREAD

**Issue by liangpengfei** [Xuanwo/WebsitesForStudents#43]
鉴于github上程序员还是占大多数，而且项目中的网站也大多是与计算机相关的，所以我感觉现在可以单独开启一个程序员专栏，这样更容易分类整理，只是一个建议，看看大家的想法。

**Comment by Xuanwo** [comment]
我也觉得程序员的网站多得有些失衡，不如我们可以把一些专业性比较强，学生阶段一般不接触的内容从这个库中分离出去。

我创建了一个新的[项目](https://github.com/Xuanwo/WebsitesForProgrammer)，你们觉得是另外开一个项目还是设立一个专栏更好？

**Comment by liangpengfei** [comment]
@Xuanwo 我感觉还是在之前的这个项目中独立一个专栏要好一些。这样就不至于把程序员和普通的学生分的太远，所以其他专业的学生也有可能会了解一些比较好的资源。

**Comment by Xuanwo** [comment]
@liangpengfei 恩，我来想想怎么样安排这些内容

**Comment by noname007** [comment]
这种东西，感觉，一般都无解。分类划分什么的建议可以参考图书馆图书划分。。

**Comment by lushl9301** [comment]
不好搞的。。。

**Comment by Xuanwo** [comment]
我也觉得分类这玩意儿。。。博大精深。。`不重不漏，便于查找`。。。

**Comment by noname007** [comment]
`不重不漏，便于查找` 谈何容易，按照生物界门纲目科属种这种划分方式或许还有点希望。。。

**Comment by matthewgao** [comment]
是个好主意

**Comment by Xuanwo** [comment]
求科普**生物界门纲目科属种**怎么应用到网站分类。。

**Comment by noname007** [comment]
牛皮吹大了, :smile:。其实是开的玩笑。个人的想法是一切都在演变，标签打的比较贴合、搜索、匹配、推荐做的很好的话，问题不解决了吗。豆瓣，谷歌，这两个东西感觉就是解决这种问题挺好的东西。如果比较少就几百条，稍微分分类，人还是能接受的。如果真的很多，真么分查起来都很麻烦，和去没有检索机器的图书馆找书区别不大。做个好点的检索引擎，世界上好多问题都可以解决了。图书馆找书、文献检索。。。最重要的是这个问题也解决了。 :sweat_smile:

**Comment by liangpengfei** [comment]
@noname007 好像说的也是，这个分类确实是不好分啊。。
