### ISSUE TITLE
关于科学上网工具Lantern的讨论

### ISSUE THREAD

**Issue by liangpengfei** [Xuanwo/WebsitesForStudents#45]
Lantern是一款非常不错的科学上网工具，是我之前用的最好用的，但是不幸的是，这款由美国政府投资的工具今天也不能用了。。。而且连接后还会造成无法打开国内的网站，很伤心啊。。看来应该移除这个了。

**Comment by Xuanwo** [comment]
Sad，已经不能用了么？。。

**Comment by liangpengfei** [comment]
恩，在我这里是不行的。。不知道大家是不是都有这个问题。。

**Comment by Xuanwo** [comment]
不可访问- -，我先移除了~
